
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: albertoarroyo
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbarroyo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data